name: 02 - Workflow Filtro

on:
  push:
    branches: 'FEAT/**'

jobs:
  echo:
    runs-on: unbuntu-latest
    steps:
      - name: Exibir o evento
        run: echo "Workflow disparado por ${{ github.event_name }}"